/**
 * Generate .env.secrets file from secrets.config.json
 * This file contains op:// URIs that can be used with 'op run'
 */

import { writeFileSync } from "fs";
import { resolve } from "path";
import chalk from "chalk";
import { loadSecretsConfig } from "../lib/secrets-config.js";

async function generate() {
  try {
    const config = loadSecretsConfig();
    const envPath = resolve(process.cwd(), ".env.secrets");

    let content = "# Generated by 'npm run secrets:generate'\n";
    content += "# This file contains 1Password URIs and is safe to commit if needed,\n";
    content += "# but is gitignored by default to keep the root clean.\n\n";

    for (const secret of config.secrets) {
      // Add the original name
      content += `${secret.name}="${secret.opPath}"\n`;

      // If it's a TF_VAR_, also add the lowercase version for Terraform
      // e.g. TF_VAR_PROXMOX_API_TOKEN -> TF_VAR_proxmox_api_token
      if (secret.name.startsWith("TF_VAR_")) {
        const varName = secret.name.substring(7); // After "TF_VAR_"
        const terraformName = `TF_VAR_${varName.toLowerCase()}`;

        if (terraformName !== secret.name) {
          content += `${terraformName}="${secret.opPath}"\n`;
        }
      }
    }

    writeFileSync(envPath, content);
    console.log(chalk.green(`✓ Generated ${envPath}`));
  } catch (error) {
    console.error(chalk.red("✗ Failed to generate .env.secrets:"), error);
    process.exit(1);
  }
}

generate();
